Renamed server.start to server.install
bokeh/bokeh pull request #11974
Opened 2022-01-25 03:52 UTC by NaincyKumariKnoldus

Hye! I have renamed server.start to server.install. Please review this!
fixes #11882

2022-01-25 04:01 UTC, bryevdv requested changes

2022-01-25 04:01 UTC, bryevdv commented on bokeh/_testing/plugins/file_server.py
> +    server.install()
This is the `start` method of a Python built-in `SimpleWebServer`, not a Bokeh `Server` object (change should be reverted)

2022-01-25 04:04 UTC, bryevdv commented
Hi @NaincyKumariKnoldus Thanks for your PR. It looks like a blanket search-and-replace has swept up some unrelated places that should not be changed. I have left comments above. Additionally the actual primary task are:

* rename the existing `start` method on `BaseServer` to `install`
* add a new `start` method that calls `install` and also calls `deprecated` to issue a deprecation warning

and it does not appear either of those has been done. Let me know if there are further details I can clairfy

2022-01-25 04:11 UTC, NaincyKumariKnoldus commented
Hey @bryevdv I have reverted the changes as you suggested. Review it now!

2022-01-25 22:05 UTC, bryevdv commented on sphinx/docserver.py
> +    server.install()
Here is another one that must be reverted. This is a Python `threading.Thread` not a Bokeh `Server`

2022-01-25 22:06 UTC, bryevdv commented on bokeh/server/server.py
> +            http_server.install(opts.num_procs)
Another one. This is a tornado `HTTPServer` not a Bokeh `Server` or `BaseServer`

2022-01-25 22:10 UTC, bryevdv commented
@NaincyKumariKnoldus there were some more instances that must be reverted. I'd like to point out that lots of tools and libraries have a "start" method. However, the only ones to be changes are the ones on Bokeh obejcts:

* `BaseServer`
* `Server`

So you need to do more than a blind search and replace. You need to actually examine all the places that a "start" is called, and verify that it is on a Bokeh class, and not somethings else.

Besides that, there is still the other wort that has not been done. It is described in the issue, and I have tried to describe a bit more detail above. To reiterate:

>  Additionally the actual primary task are:
> 
> * rename the existing start method on BaseServer to install
> * add a new start method that calls install and also issues a deprecation warning stating to use install instead

This PR will not be mergeable until that part is done.

2022-01-26 04:43 UTC, NaincyKumariKnoldus commented
Hey @bryevdv Made the requested changes again. Review it!

2022-01-26 18:50 UTC, bryevdv commented
Hi @NaincyKumariKnoldus You made the changes at the call sites, but you still have not made any changes to rename the function definition (which is why all the unit test jobs are failing). The PR will not be mergable until the function definition is rename, and tests are passing.  Please let me know if there is any question about this part of the work I can elaborate on.

2022-01-27 03:32 UTC, NaincyKumariKnoldus commented
Hey @bryevdv again any changes is needed? what to change now

2022-01-27 16:05 UTC, bryevdv commented
@NaincyKumariKnoldus I have already described the remaining work required in comments above, multiple times.

2022-02-03 19:08 UTC, bryevdv commented
Closing due to lack of response and continued miscommunication.

2022-02-03 19:08 UTC, closed without merging