Added metadata to examples (#11765)
bokeh/bokeh pull request #12697
Opened 2022-12-27 17:39 UTC by Christophers27

Added metadata to examples/basic/lines/line_single.py
Partially addresses issue: #11765

2023-01-01 04:11 UTC, bryevdv requested changes
Hi @Christophers27 thanks for the PR! Just a couple of minor changes

2023-01-01 04:11 UTC, bryevdv commented on examples/basic/lines/line_single.py
> +'''
```suggestion

'''
```

2023-01-01 04:11 UTC, bryevdv commented on examples/basic/lines/line_single.py
> +    :keywords: line, glyph, straight
We usually stick to nouns/concepts for keywords 
```suggestion
    :keywords: line, glyph
```

2023-01-10 10:35 UTC, Christophers27 commented
Hi @bryevdv I committed the changes you asked but it seems that it caused some errors? Sorry I haven't been able to figure out why after some time.

2023-01-15 14:24 UTC, closed without merging