Added metadata to examples
bokeh/bokeh pull request #12743
Opened 2023-01-15 14:29 UTC by Christophers27

Added metadata to examples/basic/lines/line_single.py
Partially addresses issue #11765

2023-01-21 01:08 UTC, Christophers27 commented
Hi @bryevdv, I managed to fix the issues from the previous request, is this up to standard?

2023-01-23 17:50 UTC, bryevdv commented
@Christophers27 thanks for your patience, my dev laptop is out for repair. I will be able to look at this later this week (or @tcmetzger might be able o sooner)

2023-01-24 19:41 UTC, bryevdv requested changes
@Christophers27 just some very minor suggestions, thanks for the PR!

2023-01-24 19:41 UTC, bryevdv commented on examples/basic/lines/line_single.py
> +by mapping straight linesbetween defined points.
minor edits:
```suggestion
demonstrates the use of the ``line`` method to make a graph
by drawing straight lines between defined points.
```

2023-01-27 17:40 UTC, bryevdv commented on examples/basic/lines/line_single.py
> +by mapping straight linesbetween defined points.
I'm going to go ahead and commit the suggestion above so this can be  merged today. Thanks for the PR @Christophers27 !

2023-01-27 17:40 UTC, bryevdv approved these changes

2023-01-27 19:25 UTC, merged

2023-01-27 20:38 UTC, Christophers27 commented
Hi @bryevdv, thanks so much for the support! I apologize for not answering, schoolwork has been taking up all of my attention lately.

2023-01-28 03:18 UTC, bryevdv commented
Good luck with your studies!