Added metadata to tap.py for Tap Plots
bokeh/bokeh pull request #12908
Opened 2023-03-07 13:51 UTC by BhaswatiRoy

Fix: https://github.com/bokeh/bokeh/issues/11765

Added metadata for Tap Plots in tap.py file

2023-03-08 06:17 UTC, bryevdv commented
Thanks for the PR @BhaswatiRoy  FYI @tcmetzger has indicated he should be able to review this PR by the end of the week

2023-03-08 06:43 UTC, BhaswatiRoy commented
> Thanks for the PR @BhaswatiRoy FYI @tcmetzger has indicated he should be able to review this PR by the end of the week

thanks @bryevdv for informing

2023-03-10 06:08 UTC, tcmetzger requested changes
Thank you, I left some small comments in the review!

2023-03-10 06:08 UTC, tcmetzger commented on examples/plotting/tap.py
> +''' A interactive numerical tap plot based on simple Python array of data.
```suggestion
''' An interactive numerical tap plot based on a simple Python array of data.
```

2023-03-10 06:08 UTC, tcmetzger commented on examples/plotting/tap.py
> +    One particiular datapoint can be focused by tapping on it.
```suggestion
    You can select any datapoint by tapping on it. 
```

2023-03-10 06:08 UTC, tcmetzger commented on examples/plotting/tap.py
> +    This highlights that datapoint, and displays other datapoints in faded color.
```suggestion
    This highlights that datapoint and displays all other datapoints in a faded color.
```

2023-03-10 06:12 UTC, BhaswatiRoy commented
Thanks @tcmetzger for the suggestions, I have accepted the changes

2023-03-10 06:41 UTC, tcmetzger requested changes
Sorry, there is one more thing that I overlooked earlier!

2023-03-10 06:41 UTC, tcmetzger commented on examples/plotting/tap.py
> +    :refs: :ref:`ug_basic_tap`
```suggestion
    :refs: :ref:`ug_interaction_tools_clicktap`
```
I just now checked the ref - this needs to be an actual reference from the RST documentation. This is a bit obscure sometimes, unfortunately! In this case, the reference is from `tools.rst`, linking to https://docs.bokeh.org/en/latest/docs/user_guide/interaction/tools.html#click-tap-tools

2023-03-10 06:50 UTC, BhaswatiRoy commented
Thanks for pointing out @tcmetzger, I have corrected that.

2023-03-10 06:52 UTC, tcmetzger requested changes

2023-03-10 06:52 UTC, tcmetzger commented on examples/plotting/tap.py
> +    :apis: bokeh.plotting.figure, bokeh.plotting.show, bokeh.models.TapTool
```suggestion
    :apis: bokeh.plotting.figure, bokeh.io.show, bokeh.models.TapTool
```
And this one needs to be for https://docs.bokeh.org/en/latest/docs/reference/io.html#bokeh.io.show - sorry for the multiple requests!

2023-03-10 06:53 UTC, tcmetzger commented on examples/plotting/tap.py
> +    :apis: bokeh.plotting.figure, bokeh.plotting.show, bokeh.models.TapTool
The best way to verify these api paths is looking up the method or class in the reference guide https://docs.bokeh.org/en/latest/docs/reference.html

2023-03-10 06:56 UTC, BhaswatiRoy commented
done!!

2023-03-10 06:58 UTC, tcmetzger commented
Thank you!!

2023-03-10 07:04 UTC, tcmetzger approved these changes

2023-03-10 07:27 UTC, merged