added metadata to standalone examples
bokeh/bokeh pull request #12906
Opened 2023-03-07 10:10 UTC by Soot3

I edited examples/interaction/ customjs_for_hover and customjs_for_selection

- [x] issues: fixes #11765

2023-03-07 10:18 UTC, Soot3 reviewed
removed trailing spaces

2023-03-07 18:18 UTC, bryevdv requested changes
Thanks for the PR! Just a few very small comments

2023-03-07 18:18 UTC, bryevdv commented on examples/interaction/js_callbacks/customjs_for_hover.py
> +    :apis: bokeh.plotting.figure.segment, bokeh.plotting.figure.circle, bokeh.plotting.figure.add_tools, bokeh.models.HoverTool, bokeh.models.sources.ColumnDataSource, bokeh.models.callbacks.CustomJS
The APIs line can get very long unless we keep it narrowly focuses, let's keep this one related to hover/callbacks
```suggestion
    :apis: bokeh.plotting.figure.add_tools, bokeh.models.HoverTool, bokeh.models.sources.ColumnDataSource, bokeh.models.callbacks.CustomJS
```

2023-03-07 18:18 UTC, bryevdv commented on examples/interaction/js_callbacks/customjs_for_selection.py
> +    :apis: bokeh.plotting.figure.circle, bokeh.layouts.row, bokeh.model.Model.js_on_change, bokeh.models.sources.ColumnDataSource, bokeh.models.callbacks.CustomJS
similar observation as above
```suggestion
    :apis: bokeh.model.Model.js_on_change, bokeh.models.sources.ColumnDataSource, bokeh.models.callbacks.CustomJS
```

2023-03-07 18:18 UTC, bryevdv commented on examples/interaction/js_callbacks/customjs_for_selection.py
> +'''
```suggestion

'''
```
blank line at the end to be consistent with existsing docstrings

2023-03-07 18:18 UTC, bryevdv commented on examples/interaction/js_callbacks/customjs_for_hover.py
> +'''
```suggestion

'''
```
blank line at the end

2023-03-07 18:19 UTC, bryevdv requested changes

2023-03-07 18:19 UTC, bryevdv commented on examples/interaction/js_callbacks/customjs_for_selection.py
> +This example demonstrates selecting highlighted points on a graph.
```suggestion
using Custom Javascript.

This example demonstrates selecting highlighted points on a graph.
```
maybe a blank line if this introduces a new paragraph

2023-03-07 18:19 UTC, bryevdv commented on examples/interaction/js_callbacks/customjs_for_hover.py
> +This example demonstrates adding links between points on a graph.
```suggestion
using Custom Javascript.

This example demonstrates adding links between points on a graph.
```
similar blank line between paragraphs

2023-03-08 11:56 UTC, Soot3 commented
I understand. Thank you

2023-03-11 17:16 UTC, bryevdv approved these changes

2023-03-11 17:17 UTC, bryevdv commented
Thanks for the PR @Soot3 !

2023-03-11 17:17 UTC, merged