Added metadata to legends.py
bokeh/bokeh pull request #12920
Opened 2023-03-08 04:57 UTC by chinmaychahar

Added metadata to legends.py in examples/models/legends.py

- [x] issues: addresses #11765

2023-03-08 05:03 UTC, bryevdv commented
Hi @chinmaychahar FYI it is not necessary to close PRs and open new ones to make changes. You can make and commit new changes in the existing branch, and then `git push` them from the same branch. Then GitHub will update the existing PR. This is preferable, so that that there is a chain of continuity for reviews.

2023-03-08 05:19 UTC, chinmaychahar commented
> Hi @chinmaychahar FYI it is not necessary to close PRs and open new ones to make changes. You can make and commit new changes in the existing branch, and then `git push` them from the same branch. Then GitHub will update the existing PR. This is preferable, so that that there is a chain of continuity for reviews.

Hey, thanks for mentioning that. I actually had to delete the previous fork because there were some issues with the local setup. That's why deleting and creating the previous fork closed the PR and I had to reopen a new one. Hope that's okay

2023-03-08 06:16 UTC, bryevdv commented
@chinmaychahar 👍 no worries, FYI @tcmetzger has indicated he should be able to review this PR by the end of the week

2023-03-10 05:27 UTC, tcmetzger requested changes
Thank you! I only have two small requests!

2023-03-10 05:27 UTC, tcmetzger commented on examples/models/legends.py
> +.. bokeh-example-metadata::
Please add a blank line above the `.. bokeh-example-metadata::` section

2023-03-10 05:27 UTC, tcmetzger commented on examples/models/legends.py
> +    :apis: bokeh.core.enus.LegendLocation, bokeh.io.show, bokeh.models.Circle, bokeh.models.ColumnDataSource, bokeh.models.DataRange1d, bokeh.models.Plot
How about adding bokeh.models.Legend to this list?

2023-03-10 05:28 UTC, tcmetzger commented on examples/models/legends.py
> +The legend can be defined in terms of title, shape and orientation. This graphs shows sin and cos graph.
```suggestion
The legend can be defined in terms of title, shape and orientation. This graph shows sin and cos graph. 
```
Please use singular

2023-03-10 05:33 UTC, tcmetzger commented on examples/models/legends.py
> +'''This example shows different ways to place legends on a graph using LegendLocation.
This example is not using LegendLocation to place legends. Rather, it is using the Legend object to place legends in different locations, all of which are included in the enum LegendLocation.

How about:

```suggestion
'''This example shows different ways to place legends on a graph using the different location values included in the enumeration ``LegendLocation``. 
```

2023-03-10 05:38 UTC, tcmetzger commented on examples/models/legends.py
> +The legend can be placed at defined axes, fixed locations, name locations and side panels.
This example only demonstrates placing legends in the named locations included in the enumeration. You can just omit this sentence.

```suggestion

```

2023-03-10 07:01 UTC, tcmetzger commented on examples/models/legends.py
> +    :apis: bokeh.core.enus.LegendLocation, bokeh.io.show, bokeh.models.Circle, bokeh.models.ColumnDataSource, bokeh.models.DataRange1d, bokeh.models.Plot
```suggestion
    :apis: bokeh.core.enums.LegendLocation, bokeh.io.show, bokeh.models.Circle, bokeh.models.ColumnDataSource, bokeh.models.DataRange1d, bokeh.models.Plot
```

2023-03-10 07:13 UTC, tcmetzger commented on examples/models/legends.py
> +    :keywords: sin, cos, pi, linspace, LegendLocation
You could add a reference to the user guide here, like:

```suggestion
    :refs: :ref:`ug_styling_plots_legends`
    :keywords: sin, cos, pi, linspace, LegendLocation
```

2023-03-10 09:28 UTC, chinmaychahar commented
I've made the changes accordingly. Please let me know if I missed on something

2023-03-11 17:15 UTC, bryevdv commented
HI @chinmaychahar this is almost ready, there are just some linter issues to deal with:

```
E        File contains trailing whitespace: examples/models/legends.py, line 1.
E         File contains trailing whitespace: examples/models/legends.py, line 2.
E         File contains trailing whitespace: examples/plotting/tap.py, line 2
```
That last one is not your fault, and is fixed in another PR, but the simplest thing here is probably just to delete the trailing space in your branch. 

```
E         examples/models/legends.py:5:1: RUF002 [*] Docstring contains ambiguous unicode character ` ` (did you mean ` `?)
E         examples/models/legends.py:5:3: RUF002 [*] Docstring contains ambiguous unicode character ` ` (did you mean ` `?)
E         examples/models/legends.py:5:166: E501 Line too long (175 > 165 characters)
E         examples/models/legends.py:6:1: RUF002 [*] Docstring contains ambiguous unicode character ` ` (did you mean ` `?)
E         examples/models/legends.py:6:3: RUF002 [*] Docstring contains ambiguous unicode character ` ` (did you mean ` `?)
```
it looks like some unicode spaces crept in an should be replaces with a basic space character, also the `apis` line is too long. I would suggest removing one or two of the references. Eventually we will hopefully auto-reference everything and won't need these manual references anyway.

2023-03-12 08:16 UTC, chinmaychahar commented
@bryevdv Thanks for the review, I made the changes.

2023-03-13 05:31 UTC, bryevdv commented
@chinmaychahar There is still a unicode space issue tripping up the linter:
```
FAILED tests/codebase/test_ruff.py::test_ruff - AssertionError: ruff issues:
  examples/models/legends.py:5:1: RUF002 [*] Docstring contains ambiguous unicode character ` ` (did you mean ` `?)
  examples/models/legends.py:5:3: RUF002 [*] Docstring contains ambiguous unicode character ` ` (did you mean ` `?)
  examples/models/legends.py:6:1: RUF002 [*] Docstring contains ambiguous unicode character ` ` (did you mean ` `?)
  examples/models/legends.py:6:3: RUF002 [*] Docstring contains ambiguous unicode character ` ` (did you mean ` `?)
  Found 4 errors.
  [*] 4 potentially fixable with the --fix option.
```

I think if you run `ruff --fix .` in the top level of the repo, it might fix those issues for you (and then you can commit and push the changes that `ruff` made)

2023-03-14 09:22 UTC, chinmaychahar commented
@bryevdv there were some rebase issues but I executed `ruff --fix .` this time, like you suggested and hopefully it should it work.

2023-03-16 01:11 UTC, bryevdv approved these changes

2023-03-16 01:14 UTC, bryevdv requested changes
@chinmaychahar I was about to merge but then I noticed the unrelated changed to [examples/styling/mathtext/latex_schrodinger.py](https://github.com/bokeh/bokeh/pull/12920/files#diff-887c7c260e38d9157d80345ed69b1aa90dc3e6212fd8cd088a890034bed59da1) are in this PR for some reason. Can you remove that change? We should keep PRs on-topic, also changing those colors will require generating new thumbnails so that should all happen in a dedicated PR.

2023-03-16 06:55 UTC, chinmaychahar commented
@bryevdv yes, you're right. I've removed those changes from this branch

2023-03-16 16:47 UTC, bryevdv commented on examples/styling/mathtext/latex_schrodinger.py
> +    p.varea(q, ylower, E_v, fill_color= "orange")
```suggestion
    p.varea(q, yupper, E_v, fill_color="coral")
    p.varea(q, ylower, E_v, fill_color="orange")
```

2023-03-16 16:48 UTC, bryevdv commented
@chinmaychahar almost there, the example file still showing up in the PR due to formatting differences from the original. I've left a suggestion.

2023-03-16 17:00 UTC, chinmaychahar commented
Done, apologies for the minor errors every time! @bryevdv

2023-03-16 18:17 UTC, bryevdv approved these changes

2023-03-16 18:19 UTC, bryevdv commented
No apologies necessary @chinmaychahar OSS is always an iterative process, thanks for the PR!

2023-03-16 18:19 UTC, merged