Added metadata to colors.py
bokeh/bokeh pull request #12930
Opened 2023-03-08 15:04 UTC by Aman-Jamshed

- [x] issues: fixes #11765 

Added metadata to colors.py in examples/models/colors.py

2023-03-08 21:39 UTC, bryevdv approved these changes

2023-03-08 21:40 UTC, bryevdv commented
This LGTM but @tcmetzger can also take a look over towards the end of this week

2023-03-10 06:02 UTC, tcmetzger requested changes
Thank you, just two very small requests!

2023-03-10 06:02 UTC, tcmetzger commented on examples/models/colors.py
> +of same color together using bokeh groups.
```suggestion
of the same color together using Bokeh groups.
```
Please capitalize Bokeh (https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html#commonly-used-terms)

2023-03-10 07:14 UTC, tcmetzger approved these changes
Thank you!

2023-03-10 07:14 UTC, merged