Improved meta data of Band Plots
bokeh/bokeh pull request #12998
Opened 2023-03-20 13:15 UTC by BhaswatiRoy

Fix: https://github.com/bokeh/bokeh/issues/11765

Metadata of Band Plots required some improvements for better detailing, and inclusion of API references.

2023-03-21 12:04 UTC, mosc9575 commented on examples/basic/annotations/band.py
> +''' A interactive numerical band plot based on Simple Python array of data.
```suggestion
''' An interactive numerical band plot based on simple Python array of data.
```

2023-03-21 12:04 UTC, mosc9575 commented on examples/basic/annotations/band.py
> +    The line passes through the mean of the area covered by the Band
```suggestion
    The line passes through the mean of the area covered by the Band.
```

2023-03-21 12:07 UTC, BhaswatiRoy commented
Hello @mosc9575 
Thanks for the suggestions, I have made the changes

2023-03-22 02:08 UTC, bryevdv requested changes
Thanks @BhaswatiRoy just a few suggestions!

2023-03-22 02:08 UTC, bryevdv commented on examples/basic/annotations/band.py
> +    :keywords: bandplot, figure, scatter, line, Band, add_layout, rolling
I'd suggest paring this down a bit:
```suggestion
    :keywords: figure, scatter, line, band, layout
```
Unfortunately we don't yet have any actual standards for what goes in "keywords" but so far they have usually been more general than specific APIs. @tcmetzger maybe we can sit down sometime soon and actually try to define style guides for keyords?

2023-03-22 02:08 UTC, bryevdv commented on examples/basic/annotations/band.py
> +    The line passes through the mean of the area covered by the Band.
```suggestion
    The line passes through the mean of the area covered by the band.
```

2023-03-22 11:48 UTC, BhaswatiRoy commented
Thanks @bryevdv for the suggestions, I have made the changes

2023-03-22 16:32 UTC, bryevdv approved these changes

2023-03-22 16:35 UTC, bryevdv commented
Thanks @BhaswatiRoy !

(And thanks @mosc9575 for the review, BTW would you like to be added to @bokeh/dev?)

2023-03-22 16:35 UTC, merged

2023-03-22 16:45 UTC, mosc9575 commented
@bryevdv Sure. That would be an honor for me.

2023-03-22 16:48 UTC, bryevdv commented
invite sent!