Added metadata to text.py
bokeh/bokeh pull request #13000
Opened 2023-03-20 16:55 UTC by Azaya89

I added metadata to examples/plotting/text.py

- [x] issues: fixes #11765 
- [x] tests added / passed

2023-03-21 12:02 UTC, mosc9575 commented on examples/plotting/text.py
> +''' A grid plot using descriptive test. This example demonstrates
```suggestion
''' A grid plot using descriptive text. This example demonstrates
```

2023-03-21 12:14 UTC, Azaya89 commented on examples/plotting/text.py
> +''' A grid plot using descriptive test. This example demonstrates
Changes executed.

2023-03-22 02:03 UTC, bryevdv requested changes
Thanks @Azaya89 just a few comments

2023-03-22 02:03 UTC, bryevdv commented on examples/plotting/text.py
> +demonstrates how to change the angle of the texts in the plot.
small edit suggestion:
```suggestion
demonstrates how to change the angle of text in a plot.
```

2023-03-22 02:03 UTC, bryevdv commented on examples/plotting/text.py
> +    :keywords: Slider, gridplot, line, text
AFAIK we have not capitalized keywords anywhere else 
```suggestion
    :keywords: slider, gridplot, line, text
```

2023-03-22 02:03 UTC, bryevdv commented on examples/plotting/text.py
> +    :refs: :ref:`ug_basic_layouts_gridplot`
This section also seems relevant:
```suggestion
    :refs: :ref:`ug_basic_layouts_gridplot`, :ref:`ug_styling_text_properties`
```

2023-03-22 02:53 UTC, bryevdv commented
Hi @Azaya89 unfortunately I had not noticed but there is already an earlier PR open to add metadata to this particular example #12990 accordingly I will close this later PR. Fortunately there a lots of examples that can use your attention!

2023-03-22 02:53 UTC, closed without merging