Updated lines.rst
bokeh/bokeh pull request #13017
Opened 2023-03-23 09:16 UTC by KesharwaniArpita

2023-03-24 01:00 UTC, bryevdv requested changes
Thanks @KesharwaniArpita only two very tiny comments

2023-03-24 01:00 UTC, bryevdv commented on docs/bokeh/source/docs/user_guide/basic/lines.rst
> +.. _ug_basic_lines_with_missing_points:
just stylistically, this would be more consistent with the way we usually elide connective words in ref anchors
```suggestion
.. _ug_basic_lines_missing_points:    
```

2023-03-24 01:00 UTC, bryevdv commented on docs/bokeh/source/docs/user_guide/basic/lines.rst
> +.. _ug_basic_lines_with_parameter:
style nit
```suggestion
.. _ug_basic_lines_parameterized: 
```

2023-03-24 03:37 UTC, KesharwaniArpita commented
@bryevdv , I have commited the required changes,

2023-03-24 06:17 UTC, bryevdv approved these changes

2023-03-24 06:17 UTC, bryevdv commented
Thanks @KesharwaniArpita !

2023-03-24 06:19 UTC, bryevdv commented
@KesharwaniArpita I was slightly too hasty, it looks like several lines ended up with trailing space are tripping up the linter:
```
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 17.
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 18.
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 51.
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 52.
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 62.
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 63.
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 110.
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 124.
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 138.
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 139.
```
should be good after these are corrected. Please run the codebase tests locally before pushing (we have limited test running compute-hours and lots of folks are working in the repo at once presently)

2023-03-24 06:50 UTC, bryevdv commented
FWIW most editors have a configuration that can be enabled to automatically remove all trailing spaces that is often helpful IMO.

2023-03-25 10:23 UTC, KesharwaniArpita commented
@bryevdv , i have removed the whitespaces,  it will work fine now.
can we move back to #12989 ?

2023-03-25 16:00 UTC, bryevdv commented
Hi @KesharwaniArpita there is still one line with trailing space that is tripping up the linter:
```
E         File contains trailing whitespace: docs/bokeh/source/docs/user_guide/basic/lines.rst, line 63.
```
FYI I am not sure what editor or IDE you are using, but many editors have a configurable setting that will automatically remove trailing space when every time you save a file. I find it helpful to turn on that setting, so as to avoid these issues automatically. Also it is possible to run these codebase tests locally with `pytest` before pushing, they are located in `tests/codebase`

2023-03-29 13:40 UTC, KesharwaniArpita commented
@bryevdv

2023-03-29 15:39 UTC, bryevdv requested changes
Same as the other PR, some git issue resulting in diff noise in the changes. Please reach out on slack if you want to discuss any git commands, etc.

2023-03-29 15:39 UTC, bryevdv commented on docs/bokeh/source/docs/user_guide/basic/lines.rst
> +>>>>>>> 53e2b9d626402c06af78b0f2aa9c0a709e4d546c
diff output noise needs to be resolved

2023-03-29 15:41 UTC, bryevdv commented on examples/basic/lines/arcs.py
> +'''
Also this change should belong to the other PR? Or do you intend to merge into a single PR? (either way typo on first line "A ac" -> "An arc")

2023-04-02 01:42 UTC, bryevdv commented
I'm going to assume that since you wanted to resolve the other PR with similar issues by opening a new PR, that that will also be the case here.

2023-04-02 01:42 UTC, closed without merging