Line select metadata
bokeh/bokeh pull request #13022
Opened 2023-03-23 19:44 UTC by chinmaychahar

Metadata for examples/plotting/line_select.py was outdated so I updated it acc. to the set template 

- [x] issues: fixes #11765

2023-03-24 00:39 UTC, bryevdv requested changes
Thanks @chinmaychahar a few comments

2023-03-24 00:39 UTC, bryevdv commented on examples/plotting/line_select.py
> +""" Example demonstrating the picking of line objects -using customJS.
```suggestion
""" Example demonstrating line selection together with with customJS.
```

2023-03-24 00:39 UTC, bryevdv commented on examples/plotting/line_select.py
> +    :refs: :ref:`ug_basic_lines_line_multi`,:ref:`ug_interaction_js_callbacks`
errant ref anchor
```suggestion
    :refs: :ref:`ug_basic_lines_multi`, :ref:`ug_interaction_js_callbacks`
```

2023-03-24 00:39 UTC, bryevdv commented on examples/plotting/line_select.py
> +    :keywords: line, taptool, customjS
typo
```suggestion
    :keywords: line, taptool, customjs
```

2023-03-24 00:52 UTC, bryevdv commented
@chinmaychahar it looks like #13019 was already just previously opened almost at the same time by @Azaya89 to for this file. I'd like for the two of you to discuss and let me know which PR to keep, perhaps you can collaborate and both add commits to one PR (by way of comment code suggestions).

2023-03-24 03:50 UTC, chinmaychahar commented
Sure, I'd be happy to collaborate and discuss :D 

@Azaya89 thanks for the changes you suggested in your PR. I went through them and they were almost identical to mine so I don't mind going forward with either of the PRs. 

Let me know your thoughts and we can incorporate the changes suggested by @bryevdv in the PR too if you're okay with it. Cheers!

2023-03-24 09:19 UTC, Azaya89 commented
> Sure, I'd be happy to collaborate and discuss :D
> 
> @Azaya89 thanks for the changes you suggested in your PR. I went through them and they were almost identical to mine so I don't mind going forward with either of the PRs.
> 
> Let me know your thoughts and we can incorporate the changes suggested by @bryevdv in the PR too if you're okay with it. Cheers!

Oh yeah, I think 

> Sure, I'd be happy to collaborate and discuss :D
> 
> @Azaya89 thanks for the changes you suggested in your PR. I went through them and they were almost identical to mine so I don't mind going forward with either of the PRs.
> 
> Let me know your thoughts and we can incorporate the changes suggested by @bryevdv in the PR too if you're okay with it. Cheers!

Yeah, I think we can merge yours instead, since the changes suggested by @bryevdv is an improvement overall. I will go ahead and close mine now.

2023-03-24 17:42 UTC, chinmaychahar commented
> Yeah, I think we can merge yours instead, since the changes suggested by @bryevdv is an improvement overall. I will go ahead and close mine now.

Okay, I'll be making the changes requested to this PR then. Let me know if you have comments to add. Thanks!

2023-03-25 15:55 UTC, bryevdv approved these changes

2023-03-25 15:56 UTC, bryevdv commented
Thanks @chinmaychahar and @Azaya89 !

2023-03-25 15:56 UTC, merged