Tile source metadata
bokeh/bokeh pull request #13026
Opened 2023-03-24 04:58 UTC by chinmaychahar

Metadata for examples/models/tile_source.py

- [x] issues: fixes #11765

2023-03-24 05:04 UTC, chinmaychahar commented
@bryevdv One thing I struggle with every time is to find the correct metadata the `ref` section. I wanted some guidance for the same. 

For example, for this file i.e. tile_source.py the reference URL will be [this](https://docs.bokeh.org/en/latest/docs/user_guide/topics/geo.html#tile-provider-maps) so do I add the permalink to the main heading for the `ref` section here?

2023-03-24 22:21 UTC, bryevdv approved these changes

2023-03-24 22:24 UTC, bryevdv requested changes
One small comment from me @chinmaychahar but also some linter issues:
```
E         File contains trailing whitespace: examples/models/tile_source.py, line 1.
E         File contains trailing whitespace: examples/models/tile_source.py, line 2.
```
I do recommend running the codebase checks before pushing as all these issues can be caught locally

2023-03-24 22:24 UTC, bryevdv commented on examples/models/tile_source.py
> +'''
Formatting consistency with other examples (blank line after metadata)
```suggestion
    :keywords: tile source
    
'''
```

2023-03-25 15:53 UTC, bryevdv commented
Thanks @chinmaychahar !

2023-03-25 15:53 UTC, merged