Added metadata to theme_glyphs
bokeh/bokeh pull request #13047
Opened 2023-04-03 01:32 UTC by yah-yuan

Added metadata for examples\plotting\theme_glyphs.py .
Relate to issue https://github.com/bokeh/bokeh/issues/11765

2023-04-03 07:55 UTC, mosc9575 commented on examples/plotting/theme_glyphs.py
> +'''This example shows how to to create and use your custom theme in a Bokeh plot with JSON.
```suggestion
'''This example shows how to create and use your custom theme in a Bokeh plot with JSON.
```

2023-04-03 07:55 UTC, mosc9575 commented on examples/plotting/theme_glyphs.py
> +    :keywords: Custom Theme, JSON
```suggestion
    :keywords: styling, Custom Theme, JSON
```

2023-04-07 07:44 UTC, yah-yuan commented
Hi @mosc9575 , thanks for your review. I accepted the modification. Waiting for more advice.

2023-04-10 00:30 UTC, bryevdv requested changes
Thanks @yah-yuan just a few final comments then this will be good to merge

2023-04-10 00:30 UTC, bryevdv commented on examples/plotting/theme_glyphs.py
> +    :refs: :ref:`_ug_styling_using_themes_custom`
leading underscore is only for when the anchor is defined, not when it is used
```suggestion
    :refs: :ref:`ug_styling_using_themes_custom`
```

2023-04-10 00:30 UTC, bryevdv commented on examples/plotting/theme_glyphs.py
> +    :keywords: Custom Theme, JSON
we tend to use keywords sparingly, and keep lowercase
```suggestion
    :keywords: theme
```

2023-04-10 00:30 UTC, bryevdv commented on examples/plotting/theme_glyphs.py
> +
no blank line between docstring an first import
```suggestion
```

2023-04-14 15:58 UTC, bryevdv commented
Hi @yah-yuan do you expect to be able to continue with this PR?

2023-04-14 22:36 UTC, yah-yuan commented
Hi @bryevdv , sorry that I miss the last notification. And thanks for the document suggestions and I have accepted them.

I noticed some test checks do not pass. Do you think that is a problem?

2023-04-24 01:10 UTC, bryevdv commented
I think it is a spurious failure, I have restarted that one test.

2023-04-24 01:12 UTC, bryevdv commented
@yah-yuan you marked the conversations resolved, but it does not appear that any of the suggestions were actually applied (there are no new commits)

2023-05-28 17:20 UTC, pavithraes commented
@yah-yuan This PR looks close, would you be able to complete it? 

As Bryan said, the previous code review suggest didn't actually get implemented -- you can make these updates in a separate commit if you'd like :)

2023-06-01 16:19 UTC, tzhang-dev commented
Hi @pavithraes, sorry for afk for a while. I have committed the suggested changes.

2023-06-01 18:37 UTC, pavithraes approved these changes
Thanks for the updates, @yah-yuan! Looks good to me. :)

2023-06-05 05:57 UTC, bryevdv approved these changes

2023-06-06 19:12 UTC, merged

2023-06-06 19:13 UTC, bryevdv commented
Thanks @yah-yuan !