Added metadata for examples/models/toolbars2.py
bokeh/bokeh pull request #13051
Opened 2023-04-03 18:37 UTC by fllagami

All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: fixes #xxxx
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

2023-04-03 18:38 UTC, fllagami commented
Related to issue #11765

2023-04-10 00:38 UTC, bryevdv requested changes
Thanks for your patience @fllagami I've been sick recently. Just a couple of comments then this is good to merge

2023-04-10 00:38 UTC, bryevdv commented on examples/models/toolbars2.py
> +''' This example shows multiple ways to place the toolbar with respect to a grid of up to four plots.
This example happens to have four plots, but there is nothing special about that number, these locations will work with any grid size.
```suggestion
''' This example shows multiple ways to place the toolbar with respect to a grid of plots.
```

2023-04-10 00:38 UTC, bryevdv commented on examples/models/toolbars2.py
> +    :keywords: tools, toolbar, mkplot, mkgrid, layout
`mkgrid` and `mkplot` are helpers that exist only in this example, they are not relevant to anything else in a wider context
```suggestion
    :keywords: tools, toolbar, layout
```

2023-04-24 01:07 UTC, bryevdv approved these changes

2023-04-24 01:08 UTC, bryevdv commented
The documentation job failing is unrelated and will go away when this is merged (i.e. it is fixed on the main dev branch) thanks @fllagami

2023-04-24 01:08 UTC, merged