Correctly set Scatter.max_size
bokeh/bokeh pull request #13085
Opened 2023-04-15 23:51 UTC by yah-yuan

Fix of issue https://github.com/bokeh/bokeh/issues/12078 . Followed the previous PR of https://github.com/bokeh/bokeh/pull/11453 and applied to scatter view.

![image](https://user-images.githubusercontent.com/25447788/232258770-3b704151-5f34-45df-976a-eaf07bab24e6.png)

2023-04-18 13:26 UTC, mattpap requested changes
This PR needs a rebase to fix unrelated CI failure. This also needs some unit tests in bokehjs, specifically for `_hit_*` methods that `Scatter` glyph implements.

2023-04-18 13:26 UTC, mattpap commented on bokehjs/src/lib/models/glyphs/scatter.ts
> +  override _set_data(indices: number[] | null): void {
This should be moved to `MarkerView` class in `models/glyphs/marker.ts`, as it's where `size` property is defined and where it should be handleded.

2023-04-18 17:21 UTC, tzhang-dev commented
Hi @mattpap , thanks for the review and feedback. For the `_hit_*` methods, do you mean those implemented in Marker glyph? Since I found no such methods in Scatter.

Also, I did the rebase and those CI errors persist. Are they still related?

2023-04-18 17:25 UTC, bryevdv commented
> Also, I did the rebase and those CI errors persist. Are they still related? 

I think the latest two were just two flaky jobs, I have restarted them.

2023-04-20 18:19 UTC, yah-yuan commented
Hi maintainer, can I get some instruction on the design intent of the `_hit_*` method and how to unit test them? I am trying to learn from the code but maybe an initial guide will help.

2023-04-24 01:01 UTC, bryevdv commented
@yah-yuan I do believe @mattpap meant in `marker.ts` (@mattpap please confirm) 

For reference, here is a utnit test for `_hit_point` on `Rect`:

https://github.com/bokeh/bokeh/blob/9ceb505a04d60efc62f9b8de8188c6629268f791/bokehjs/test/unit/models/glyphs/rect.ts#L54-L79

2023-04-24 20:22 UTC, mattpap commented on bokehjs/src/lib/models/glyphs/marker.ts
> +    })()
With PR #12677 merged, this block can now be replaced with `const max_size = uniforms.max(this.size)` (where `uniforms` comes from `import * as uniforms from "core/uniforms"`).

2023-04-24 20:25 UTC, mattpap commented
> I do believe @mattpap meant in marker.ts (@mattpap please confirm)

Tests need to test a concrete implementation (`Marker` is abstract), so testing `Scatter` glyph is fine. One can also implement a dummy marker-like class in tests to avoid involving `Scatter` glyph in testing.

2023-05-21 21:13 UTC, mattpap approved these changes

2023-05-21 21:15 UTC, merged

2023-05-21 21:15 UTC, mattpap commented
@yah-yuan,thanks.