[BUG] Fix broken link to tools guide
bokeh/bokeh pull request #13109
Opened 2023-05-03 12:56 UTC by kshitiz305

Issue: Fixes #13108 

All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [X] issues: fixes #xxxx
- [X] tests added / passed
- [X] release document entry (if new feature or API change)

2023-05-03 13:18 UTC, mattpap requested changes

2023-05-03 13:18 UTC, mattpap commented on bokehjs/src/lib/models/tools/actions/help_tool.ts
> +      redirect: [ String, "https://docs.bokeh.org/en/latest/docs/reference/models/tools.html"],
This https://docs.bokeh.org/en/latest/docs/user_guide/interaction/tools.html is the correct link. Same in other cases.

2023-05-03 15:09 UTC, kshitiz305 commented on bokehjs/src/lib/models/tools/actions/help_tool.ts
> +      redirect: [ String, "https://docs.bokeh.org/en/latest/docs/reference/models/tools.html"],
Let me update it as the one mentioned in the issue was different

2023-05-03 17:37 UTC, mattpap approved these changes

2023-05-04 15:46 UTC, mattpap commented
@kshitiz305, thanks for fixing this.

2023-05-04 15:47 UTC, merged