Add Python 3.12 to CI
bokeh/bokeh pull request #13412
Opened 2023-10-04 20:20 UTC by ianthomas23

Now that CPython 3.12 has been released, try it out in CI in the hope that it can be included in the upcoming 3.3 release. Also added 3.12 to classifiers.

2023-10-04 21:03 UTC, mattpap commented
So close, only contourpy and matplotlib-base (required by squarify; technically matplotlib is optional, but I'm not sure if conda can handle that).

2023-10-05 08:10 UTC, ianthomas23 commented
> So close, only contourpy and matplotlib-base (required by squarify; technically matplotlib is optional, but I'm not sure if conda can handle that).

contourpy is fine, I have ensured there are python 3.12 packages on conda-forge already.

2023-10-07 23:35 UTC, bryevdv commented
It looks like the packages are working and now there is a pandas deprecation failing things:
> E   DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).

2023-10-08 11:18 UTC, ianthomas23 commented
We will have to hold off on this. The cause of the deprecation warning has been fixed in `python-dateutil` but they need to make a new release on PyPI and conda-forge containing the fix and it seems they are experiencing personnel/permissions issues dateutil/dateutil#1284.

2023-10-08 14:27 UTC, graingert commented
@ianthomas23 can you ignore the warning from the dateutil module to get this unblocked?

2023-10-08 18:41 UTC, bryevdv commented
@graingert presumably you mean here? 

https://github.com/bokeh/bokeh/blob/273f12589b14f30d7b923e15b80cd9cd9ac96ab0/pyproject.toml#L82-L108

Would that just be a line lile
```
'''ignore:datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version:DeprecationWarning''', 
```
?

2023-10-08 18:42 UTC, bryevdv commented
@bokeh/core I do think we should wait for this PR to release, it would be a bit weird to have a new major release w/o explicit 3.12 support

2023-10-08 18:54 UTC, graingert commented
No like this 

```
'''ignore:datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version:DeprecationWarning:dateutil'', 
```

2023-10-08 19:33 UTC, ianthomas23 commented
Thanks @graingert, trying it out now...

2023-10-08 20:05 UTC, bryevdv commented
Sigh. Unfortunately, the deprecation also happens in `test_defaults` which is run via a different mechanism, so that is still failing. 

But that aside, now there is also 
> ERROR tests/unit/bokeh/core/test_serialization.py - AttributeError: partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)

I will have to try to repro this conda env and see if I can see this locally.

2023-10-09 11:47 UTC, graingert requested changes

2023-10-09 11:47 UTC, graingert commented on pyproject.toml
> +    '''ignore:datetime.datetime.utcfromtimestamp():DeprecationWarning:dateutil''',
```suggestion
    '''ignore:datetime\.datetime\.utcfromtimestamp\(\):DeprecationWarning:dateutil''',
```

2023-10-09 12:02 UTC, ianthomas23 commented
Now that `pytest` is actually ignoring the warning there are no further `pandas` errors. We are left with one test failure in `test_descriptors.py` related to use of `mock`. I know nothing about `mock` so I am stopping here.

2023-10-09 12:19 UTC, graingert commented
That's a pretty easy fix the assert is currently a noop and should be `mock_get.assert_called_once_with((f, "bar", 10), {})`

2023-10-09 14:33 UTC, ianthomas23 commented
@graingert If you think it is a pretty easy fix then feel free to try it yourself.

2023-10-09 15:33 UTC, graingert commented
@ianthomas23 ok it was a bit more complicated because the noop assertion was also incorrect, and the mock_get and mock_set args were swapped around. I've fixed it with a `mock_calls == [...]` assertion

2023-10-09 16:07 UTC, ianthomas23 commented
@graingert Thanks for that. I'll close this PR then as it is superseded by #13419.

2023-10-09 16:07 UTC, closed without merging