Restored broken API links
bokeh/bokeh pull request #13528
Opened 2023-11-14 19:11 UTC by Azaya89

- [x] issues: fixes #13505 as well as some other minor clarifications in the set-up guide.
- [x] tests added / passed

2023-11-14 19:21 UTC, bryevdv commented
I'm not opposed to making these immediate changes to remove "annotation" if that gets things working, but AFAIK we still don't have any root cause for the issue, or know why some models work with "long" paths and others only work with "short" paths.

2023-11-14 20:42 UTC, Azaya89 commented
> I'm not opposed to making these immediate changes to remove "annotation" if that gets things working, but AFAIK we still don't have any root cause for the issue, or know why some models work with "long" paths and others only work with "short" paths.

tbh, I don't know why they don't work anymore either, but I noticed it was mostly the APIs with 'annotation' in the path that were broken.

2023-11-15 05:06 UTC, tcmetzger requested changes
Looks great, thank you! 
I believe there is only one link that isn't working yet (see comment)!

2023-11-15 05:06 UTC, tcmetzger commented on examples/interaction/legends/legend_hide.py
> +    :apis: bokeh.plotting.figure.line, bokeh.palettes.brewer-palettes
This link still doesn't seem to show up correctly (at least in my local build) 
![image](https://github.com/bokeh/bokeh/assets/39711796/c76bbe32-2efb-4fd7-9806-99133f8cbf8a)

2023-11-15 05:06 UTC, tcmetzger commented
While reviewing this PR, I noticed https://github.com/bokeh/bokeh/issues/13529

2023-11-15 16:54 UTC, Azaya89 commented on examples/interaction/legends/legend_hide.py
> +    :apis: bokeh.plotting.figure.line, bokeh.palettes.brewer-palettes
I have shortened it now to refer to the top level `bokeh.palettes` path.

2023-11-17 17:28 UTC, bryevdv approved these changes

2023-11-17 17:32 UTC, tcmetzger approved these changes
Thank you!

2023-11-22 18:03 UTC, merged

2023-11-22 18:03 UTC, bryevdv commented
If we don't already have one, an issue or discussion about making these example link specifications consistent would be good.